version: "3.7"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    volumes:
      - nexus:/nexus-data
    environment:
      JAVA_MAX_MEM: 768m
      INSTALL4J_ADD_VM_PARAMS: -XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=1600m
    networks:
      - proxy
    ports:
      - "10010:10010" # docker
      - "10011:10011" # docker hosted
    expose:
      - 8081 # admin
    labels:
      - traefik.docker.network=proxy
      - traefik.http.routers.nexus.rule=Host("nexus.${DOMAIN}")
      - traefik.http.services.nexus.loadbalancer.server.port=8081
      - traefik.http.routers.nexus.service=nexus
      - traefik.http.routers.nexus.entrypoints=https
      - traefik.http.routers.nexus.tls=true
      - traefik.http.routers.nexus.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.registry.middlewares=traefik-compress

volumes:
  nexus:

networks:
  proxy:
    external: true
